book_id: "art_of_seduction"
title: "The Art of Seduction"
author: "Robert Greene"
domains:
  - psychology
  - seduction
default_ministers:
  - psychology
chapters:
  - id: "charm"
    title: "The Art of Charm"
  - id: "coquetry"
    title: "The Coquette"
